variables:
  GLFW_IMAGE: $CI_REGISTRY_IMAGE/glfw:$CI_COMMIT_REF_NAME

docker-image:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $GLFW_IMAGE .
    - docker push $GLFW_IMAGE

spec:
  image: $GLFW_IMAGE
  stage: test
  dependencies:
    - docker-image
  before_script:
    - crystal -v
    - shards
  script:
    - crystal spec
    - bin/ameba
    - crystal tool format --check
  cache:
    paths:
      - lib
      - bin

pages:
  image: crystallang/crystal:latest
  stage: deploy
  dependencies:
    - spec
  before_script:
    - crystal -v
    - shards
  script:
    - crystal docs
    - mv docs/ public/
  artifacts:
    paths:
      - public
  only:
    - master
